Feature3 edit task
Sindoraii/Todolist pull request #5
Opened 2022-03-24 15:47 UTC by Sindoraii

2022-03-24 17:11 UTC, Jesovile reviewed
It's a greate job. Good using of callback in ModalManager-EditModal. Good decomposition and good relations between components.

Issues I have pointed for you are about naming and code style at most.

Also like a simple suggestion. I think, it will be cool, if EditModal has 'Cancel' button and if it closes by click on 'Ok' button. It's a common behavior for modals (by my experience).

You are cool! Do not stop! )

2022-03-24 17:11 UTC, Jesovile commented on ModalManager/EditModal/edit_modal.js
> +        this.set = (taskData) => {
The same about name of the method. 'Set' what? What does it set? )))). Semantic is a key property of naming ))))

2022-03-27 14:27 UTC, Sindoraii commented on ModalManager/modalManager.js
> +        let id = null;
This id is needed like a private field for private methods. Id gets its value when user has clicked on the edit button. I can rename it like 'taskId'.What do you think about it?

2022-03-31 13:35 UTC, Jesovile commented on ModalManager/modalManager.js
> +        let id = null;
'taskId' woll be great. More understandable, as for me

2022-03-31 14:08 UTC, Jesovile requested changes
It looks better. Need to fix a few issues

2022-03-31 14:08 UTC, Jesovile commented on ModalManager/EditModal/edit_modal.css
> +*, :before,:after {
I think, it would be better to move common css-rules like this to global css-file like 'main.css'

2022-03-31 14:08 UTC, Jesovile commented on ModalManager/EditModal/edit_modal.js
> +        const h2OfHeader = document.createElement('h2');
Maybe 'subheader' would be bettere than 'h2OfHeader'?

2022-03-31 14:08 UTC, Jesovile commented on ModalManager/EditModal/edit_modal.js
> +         * @param {HTMLElement} title - input 'Task name'
HTMLElement? It looks like strings, not HTMLElements

2022-03-31 15:43 UTC, Sindoraii commented on ModalManager/EditModal/edit_modal.js
> +         * @param {HTMLElement} title - input 'Task name'
Params are HTMLElements. It is information that i want to give modalManager from EditModal by the callback. It looks like strings,but it is not strings.Also, I changed type of params in function send() too.

2022-03-31 15:44 UTC, Sindoraii commented on ModalManager/EditModal/edit_modal.css
> +*, :before,:after {
It`s a great idea.

2022-04-10 12:51 UTC, Jesovile requested changes

2022-04-10 18:02 UTC, Sindoraii commented
Edit modal has created.

2022-04-10 18:02 UTC, closed without merging